events {
    worker_connections 1024;
}

http {
    # Main website - titanic.htb
    server {
        listen 80;
        server_name titanic.htb;

        location / {
            proxy_pass http://10.20.0.11:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # Gitea server - dev.titanic.htb
    server {
        listen 80;
        server_name dev.titanic.htb;

        location / {
            proxy_pass http://10.20.0.12:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
