version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: titanic_mysql
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecureRootPass2024!
      MYSQL_DATABASE: titanic_db
      MYSQL_USER: titanic_user
      MYSQL_PASSWORD: TitanicDB_Pass_2024
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - titanic-network

  gitea:
    image: gitea/gitea:1.22.1
    container_name: titanic_gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - /home/developer/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"
    depends_on:
      - mysql
    networks:
      - titanic-network

  web:
    build: ./app
    container_name: titanic_web
    ports:
      - "5000:5000"
    volumes:
      - ./app:/opt/app
    networks:
      - titanic-network

volumes:
  mysql-data:

networks:
  titanic-network:
    driver: bridge
